
spring:

  application:
    name: ba737

  datasource:
    url: jdbc:mysql://localhost:3306/aircraftdatabase
    username: davi
    password: !@YVIU!&GE(!@G(
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update